### ISSUE TITLE
Roadmap for v1

### ISSUE THREAD

**Issue by nikoksr** [nikoksr/notify#50]
List of features/changes we want to finish before releasing an official v1 version:

- [x]   ~~Add _notify.MustSend_ method (#48)~~
- [x]   Add _context.Context_ to parameter list of _notify.Send_ - Done (#51)
- [ ]   Set standards and add a review process for new service candidates (#24)
- [ ]   Add missing usage docs
- [ ]   Add tests for all services (#1)

Please note that this list is not final.

**Comment by minhaz1217** [comment]
Hello, I just setup pingme to send discord messages. I really like it. It's a shame that it doesn't have setup guide for discord. As someone who has little knowledge about how discord bot Eco-system works, it took me a long time to setup and a lots of googling. I want to add documentation for how to setup pingme with discord. 

I think it will be something like this.

https://github.com/minhaz1217/devops-notes/tree/master/45.%20setting%20up%20pingme%20with%20discord%20for%20automated%20notification


Should I add the usage doc?
